"""initial

Revision ID: 5079cb5e3b7f
Revises: 
Create Date: 2025-12-23 02:14:21.927968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5079cb5e3b7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_ads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price_usd', sa.Integer(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('images_count', sa.Integer(), nullable=True),
    sa.Column('car_number', sa.String(length=20), nullable=True),
    sa.Column('car_vin', sa.String(length=17), nullable=True),
    sa.Column('datetime_found', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.CheckConstraint('images_count >= 0', name='check_images_count_positive'),
    sa.CheckConstraint('odometer >= 0', name='check_odometer_positive'),
    sa.CheckConstraint('price_usd >= 0', name='check_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_car_ads_active', 'car_ads', ['is_active', 'created_at'], unique=False)
    op.create_index('idx_car_ads_created_at', 'car_ads', ['created_at'], unique=False)
    op.create_index('idx_car_ads_price_odometer', 'car_ads', ['price_usd', 'odometer'], unique=False)
    op.create_index('idx_car_ads_year_brand', 'car_ads', ['year', 'brand'], unique=False)
    op.create_index(op.f('ix_car_ads_is_active'), 'car_ads', ['is_active'], unique=False)
    op.create_index(op.f('ix_car_ads_url'), 'car_ads', ['url'], unique=True)
    op.create_table('scraping_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ads_scraped', sa.Integer(), nullable=True),
    sa.Column('ads_duplicates', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraping_logs')
    op.drop_index(op.f('ix_car_ads_url'), table_name='car_ads')
    op.drop_index(op.f('ix_car_ads_is_active'), table_name='car_ads')
    op.drop_index('idx_car_ads_year_brand', table_name='car_ads')
    op.drop_index('idx_car_ads_price_odometer', table_name='car_ads')
    op.drop_index('idx_car_ads_created_at', table_name='car_ads')
    op.drop_index('idx_car_ads_active', table_name='car_ads')
    op.drop_table('car_ads')
    # ### end Alembic commands ###
